import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Link from "next/link";
import { Home, BookOpen } from "lucide-react";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("font-sans", inter.variable)}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="max-w-md mx-auto min-h-screen bg-background border-x flex flex-col relative pb-16">
          <main className="flex-1 overflow-y-auto p-4">
            {children}
          </main>

          <nav className="fixed bottom-0 w-full max-w-md bg-card border-t border-x flex justify-around items-center p-3 z-50">
            <Link href="/" className="flex flex-col items-center text-muted-foreground hover:text-primary">
              <Home size={24} />
              <span className="text-xs mt-1">Home</span>
            </Link>
            <Link href="/surahs" className="flex flex-col items-center text-muted-foreground hover:text-primary">
              <BookOpen size={24} />
              <span className="text-xs mt-1">Surahs</span>
            </Link>
          </nav>
        </div>
      </body>
    </html>
  );
}
